services:
  edm-app:
    build:
      context: .
      dockerfile: scripts/deploy/Dockerfile
    container_name: edm-web-ele
    ports:
      - "82:80"  # 將主機 82 Port 對應至容器內的 80 Port
    restart: always
    networks:
      - edm-network

networks:
  edm-network:
    driver: bridge
