server {
    listen 80;
    server_name uatedm.hwacom.com; # 系統主機網址

    location / {
        proxy_pass http://127.0.0.1:82; # 指向 Docker 映射出來的 82 Port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 解決大檔案上傳與逾時問題
        client_max_body_size 100m;
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
    }

    # 錯誤頁面處理
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
