name: Lint and Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check for merge conflicts
        if: github.event_name == 'pull_request'
        run: |
          if grep -rE "<<<<<<<|=======|>>>>>>>" . --exclude-dir=.git; then
            echo "Merge conflicts detected!"
            exit 1
          fi

      - name: Prettier and ESLint
        run: pnpm run lint
